### ISSUE TITLE
build_image_data.py error. Doesnt create .tfrecord files

### ISSUE THREAD

**Issue by FrancisSolis** [yeephycho/tensorflow_input_image_by_tfrecord#5]
python build_image_data.py
Saving results to ./
Determining list of input files and labels from ./.
Found 302 JPEG files across 3 labels inside ./.
Launching 2 threads for spacings: [[0, 151], [151, 302]]
2018-01-23 00:37:19.690943 [thread 0]: Wrote 0 images to 151 shards.
2018-01-23 00:37:19.691943 [thread 1]: Wrote 0 images to 151 shards.
2018-01-23 00:37:20.692609: Finished writing all 302 images in data set.
Determining list of input files and labels from ./.
Found 302 JPEG files across 3 labels inside ./.
Launching 2 threads for spacings: [[0, 151], [151, 302]]
2018-01-23 00:37:22.013490: Finished writing all 302 images in data set.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\Francis\AppData\Local\Programs\Python\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\Francis\AppData\Local\Programs\Python\Python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "build_image_data.py", line 264, in _process_image_files_batch
    image_buffer, height, width = _process_image(filename, coder)
  File "build_image_data.py", line 203, in _process_image
    image_data = f.read()
  File "C:\Users\Francis\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "C:\Users\Francis\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 93, in _prepare_value
    return compat.as_str_any(val)
  File "C:\Users\Francis\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\util\compat.py", line 106, in as_str_any
    return as_str(value)
  File "C:\Users\Francis\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\util\compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\Francis\AppData\Local\Programs\Python\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\Francis\AppData\Local\Programs\Python\Python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "build_image_data.py", line 264, in _process_image_files_batch
    image_buffer, height, width = _process_image(filename, coder)
  File "build_image_data.py", line 203, in _process_image
    image_data = f.read()
  File "C:\Users\Francis\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "C:\Users\Francis\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 93, in _prepare_value
    return compat.as_str_any(val)
  File "C:\Users\Francis\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\util\compat.py", line 106, in as_str_any
    return as_str(value)
  File "C:\Users\Francis\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\util\compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte

2018-01-23 00:37:19.430514: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.

>>python read_tfrecord_data.py --image_number=300 --class_number=3 --image_height=299 --image_width=299
20 files were found under current folder.
Please be noted that only files end with '*.tfrecord' will be load!
Cannot find any tfrecord files, please check the path.
Traceback (most recent call last):
  File "read_tfrecord_data.py", line 70, in <module>
    shuffle = True)
  File "C:\Users\Francis\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\input.py", line 217, in string_input_producer
    raise ValueError(not_null_err)
ValueError: string_input_producer requires a non-null input tensor

**Comment by yeephycho** [comment]
Doesn't guarantee behavior under windows, please implement porting part if you like.
